export const GENERATE_TURN = 'GENERATE_TURN'
export const CALL_TURN = 'CALL_TURN'
export const SAVE_TURN = 'SAVE_TURN'

export const SEE_CURRENT_TURN = 'SEE_CURRENT_TURN'
export const GO_NEXT_TURN = 'GO_NEXT_TURN'
export const GO_PREVIOUS_TURN = 'GO_PREVIOUS_TURN'

export const ORDER_FREE = 'ORDER_FREE'
export const ORDER_DELIVERING = 'ORDER_DELIVERING'
export const ORDER_WAITING = 'ORDER_WAITING'


<<<<<<< HEAD
export const UPDATE_TURN = 'UPDATE_TURN'
export const UPDATE_TURNS = 'UPDATE_TURNS'

export const LOAD_BACKUP_START = 'LOAD_BACKUP_START'
export const LOAD_BACKUP_SUCCESSED = 'LOAD_BACKUP_SUCCESSED'
export const LOAD_BACKUP_FAILED = 'LOAD_BACKUP_FAILED'
=======
export const UPDATE_TURN = 'UPDATE_TURN'
>>>>>>> 7c44cbce0d38351fda9f3ad2f5aed1781432bae5
